#!/usr/bin/env python2.7
"""
Scans a particular operating parameter across its range of values and writs a plot to a file
"""


class FileNameExists(Exception):
    pass


def plot_data_to_pdf(parameter_name, measurement_data, filename=None):
    """
    Plot measurements to a file
    :param parameter_name: The name of the parameter being measure
    :param measurement_data: A dictionary of parameter set values and measurements
    :param filename: An optional filename or directory name to write to
    :return: The name of the filename the plot was written to
    """
    import matplotlib.pyplot as plt
    import pylab
    from matplotlib.backends.backend_pdf import PdfPages
    import datetime
    import os.path
    # Flatten measurements data into something less natural for matplotlib...
    if filename is not None and os.path.isdir(filename):
        filename = os.path.join(filename, parameter_name + ".pdf")
    if filename is None:
        filename = parameter_name + ".pdf"
    if os.path.isfile(filename):
        raise Exception("File name exists: '{filename}' ; please make a backup and try again".format(
            filename=filename))
    with PdfPages(filename) as pdf:
        x = [k for k in measurement_data
             for _ in measurement_data[k]]
        y = [d for k in measurement_data
             for d in measurement_data[k]]
        ran = [min(x + y) - 1, max(x + y) + 1]
        pylab.ylim(ran)
        pylab.xlim(ran)
        plt.axes().set_aspect(1)
        plt.scatter(x, y, color='red')
        pylab.grid(True)
        min_value, max_value = ran
        plt.plot(np.arange(min_value, max_value + 1),
                 np.arange(min_value, max_value + 1))
        plt.title(parameter_name)
        sorted_keys = list(sorted(measurements.keys()))
        calculated_step_size = sorted_keys[1] - sorted_keys[0]
        samples_per_step = len(measurement_data[measurement_data.keys()[0]])
        info_text = 'Parameter: {parameter_name}\n' \
                    'Minimum value: {minimum_value}\n' \
                    'Maximum value: {maximum_value}\n' \
                    'Steps: {step_count}\n' \
                    'Step size: {step_size}\n' \
                    'Samples per step: {samples_per_step}'.format(
            parameter_name=parameter_name,
            minimum_value=min(x),
            maximum_value=max(x),
            step_count=len(measurement_data.keys()),
            step_size=calculated_step_size,
            samples_per_step=samples_per_step
        )
        plt.text(min_value, max_value, info_text,
                 family='monospace',
                 horizontalalignment='left',
                 verticalalignment='top')
        # Makes some assumptions about measurement_data, be careful!
        pdf_information = pdf.infodict()
        pdf_information['Title'] = parameter_name
        pdf_information['Subject'] = info_text
        pdf_information['CreationDate'] = datetime.datetime.today()
        pdf.savefig()
        plt.close()
    return filename


if __name__ == "__main__":
    from tessfpe.dhu.fpe import FPE
    import argparse
    import numpy as np

    parser = argparse.ArgumentParser(description='Scan an operating parameter and plot the result to a file')
    parser.add_argument('parameter', type=str, help="The name of the operating parameter to scan")
    parser.add_argument('low_value', type=float, nargs='?', default=None,
                        help="The low value to start the scan at, "
                             "defaults to the lowest possible value the parameter can be")
    parser.add_argument('high_value', type=float, nargs='?', default=None,
                        help="The high value to stop the scan at,"
                             " defaults to the highest possible value the parameter can be")
    parser.add_argument('--FPE-number', metavar='N', type=int, nargs='?', default=1, help='which FPE to use')
    parser.add_argument('--output', type=str, nargs='?', default=None,
                        help="The file or directory where the of the results should be output; defaults to "
                             "<parameter>.pdf or <parameter>.<number>.pdf")
    parser.add_argument('--steps', metavar='N', type=int, nargs='?', default=100,
                        help='The number of steps to take as the operating parameter is walked from its low value '
                             'to its high value (default is 100)')
    parser.add_argument('--step-size', metavar='N', type=int, nargs='?', default=None,
                        help="The size of a step to take as the operating parameter is walked from its low value "
                             "to its high value; overrides '--steps'")
    parser.add_argument('--samples-per-step', metavar='N', type=int, nargs='?', default=5,
                        help="The number of samples to take for each value the operating parameter is stepped to "
                             "(default is 5)")
    parser.add_argument('--set-defaults', action='store_true',
                        help='Set the operating parameters to their default values before running the scan')

    args = parser.parse_args()

    parameter = args.parameter

    with FPE(args.FPE_number) as fpe:
        frames_status = None
        old_values = None
        try:
            frames_status = fpe.frames_running_status
            fpe.frames_running_status = False
            old_values = fpe.ops.values
            assert parameter in old_values, "Unknown operating parameter: {}".format(parameter)
            assert parameter in fpe.house_keeping["analogue"], \
                "Parameter doesn't correspond to any known housekeeping value: {}".format(parameter)
            low_value = args.low_value if args.low_value is not None else fpe.ops[parameter].range_low
            high_value = args.high_value if args.high_value is not None else fpe.ops[parameter].range_high
            low_value, high_value = (low_value, high_value) if low_value < high_value else (high_value, low_value)
            actual_range_low, actual_range_high = \
                (fpe.ops[parameter].range_low, fpe.ops[parameter].range_high) if \
                    fpe.ops[parameter].range_low < fpe.ops[parameter].range_high else \
                    (fpe.ops[parameter].range_high, fpe.ops[parameter].range_low)
            assert actual_range_low <= low_value, "Value {low_value} out of range; " \
                                                  "lowest value is {low}".format(low_value=low_value,
                                                                                 low=actual_range_low)
            assert high_value <= actual_range_high, "Value {high_value} out of range; " \
                                                    "highest value is {high}".format(high=actual_range_high,
                                                                                     high_value=high_value)
            step_size = args.step_size if args.step_size is not None \
                else np.abs(high_value - low_value) / args.steps
            if args.set_defaults is True:
                fpe.ops.reset_to_defaults()
            measurements = {}
            for value in np.arange(low_value, high_value, step_size):
                fpe.ops[parameter].value = value
                fpe.ops.send()
                measurements[value] = []
                for _ in range(args.samples_per_step):
                    measurements[value].append(fpe.house_keeping["analogue"][parameter])
            print "Wrote {}".format(plot_data_to_pdf(parameter, measurements, filename=args.output))
        finally:
            if old_values is not None:
                for parameter in old_values:
                    if parameter + "_offset" not in old_values:
                        fpe.ops[parameter].value = old_values[parameter]
                fpe.ops.send()
            if frames_status is not None:
                fpe.frames_running_status = frames_status
